version: '3'

services:
  capsArg:
    container_name: caps
    image: caps
    restart: always
    build: .
    environment:
      NODE_ENV: development,
      # MONGO_DB: mongodb+srv://capsDB:uVoC8ECze76xJ9QN@cluster0-onwp0.mongodb.net/test?retryWrites=true&w=majority
      # SECRET_TOKEN: my_secret_token
      # URL_BASE: http://localhost:4000
      # MONGO_DB: mongodb+srv://capsDB:uVoC8ECze76xJ9QN@cluster0-onwp0.mongodb.net/test?retryWrites=true&w=majority
      SECRET_TOKEN: my_secret_token
      URL_BASE: http://localhost:4000
      URL_BASE_PRODUCTION: https://caps-arg.vercel.app/
      URL_BASE_MP: https://api.mercadopago.com/v1
      ACCESS_TOKEN: APP_USR-5829357135251490-052000-2484795b9b0db9256a78b7096bc9f5ba-570859984
      PORT: 4000
    ports:
      - 8000:4000
    logging:
      options:
        max-size: 50m
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - '27017:27017'
