export const SHOW_MESSAGE = 'SHOW_MESSAGE';
export const HIDDEN_MESSAGE = 'HIDDEN_MESSAGE';

// AUTH
export const REGISTER_OK = 'REGISTER_OK';
export const REGISTER_BAD = 'REGISTER_BAD';

export const LOGUIN_OK = 'LOGUIN_OK';
export const LOGUIN_BAD = 'LOGUIN_BAD';
export const GET_USER = 'GET_USER';
export const LOGOUT = 'LOGOUT';

// SEARCH
export const SEARCH = 'SEARCH';

// PRODUCTS
export const LIST_PRODUCTS = 'LIST_PRODUCTS';

// CART
export const LIST_CART_PRODUCTS = 'LIST_CART_PRODUCTS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const REMOVE_ALL_CART = 'REMOVE_ALL_CART';
export const INCREMENT_PRODUCT = 'INCREMENT_PRODUCT';
export const DECREMENT_PRODUCT = 'DECREMENT_PRODUCT';
export const HIDDEN_MODAL = 'HIDDEN_MODAL';
export const SUBTOTAL_PRICE = 'SUBTOTAL_PRICE';
export const GET_TOTAL_PRICE = 'GET_TOTAL_PRICE';
export const APLY_DESC = 'APLY_DESC';
export const GET_ITEMS = 'GET_ITEMS';
export const QUANTITY_PRODUCT = 'QUANTITY_PRODUCT';
